apiVersion: v1
kind: Pod
metadata:
  name: pull-test-1
  namespace: alluxio
  labels:
    app: alluxio
spec:
  nodeSelector:
    alluxio.io/oci: enabled
  containers:
    - image: alluxio.azurecr.io/pulltest/docker-nvidia-cuda:12.2.2-cudnn8-devel-ubuntu22.04
      imagePullPolicy: IfNotPresent
      name: pull-test
      command: ["sleep", "infinity"]
