{
 "title": "Alluxio-DA",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "service",
    "query": {
     "query": "label_values(up{job!=\"prometheus\"},job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job!=\"prometheus\"},instance)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"worker\"},cluster_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Storage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(alluxio_cached_storage_bytes{job=\"worker\",cluster_name=~\"$cluster\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(alluxio_cached_capacity_bytes{job=\"worker\",cluster_name=~\"$cluster\"})",
     "legendFormat": "Capacity"
    }
   ]
  },
  {
   "title": "Storage Used(%)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(alluxio_cached_storage_bytes{job=\"worker\",cluster_name=~\"$cluster\"}) / sum(alluxio_cached_capacity_bytes{job=\"worker\",cluster_name=~\"$cluster\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Cached Data",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(alluxio_data_cached_files{job=\"worker\",cluster_name=~\"$cluster\"})",
     "legendFormat": "Files"
    },
    {
     "expr": "sum(alluxio_data_cached_pages{job=\"worker\",cluster_name=~\"$cluster\"})",
     "legendFormat": "Pages"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(alluxio_data_access_bytes_sum{job=\"worker\",cluster_name=~\"$cluster\"}[5m])) or on() vector",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(irate(alluxio_ufs_data_access_bytes_total{job=\"worker\",method=\"write\",cluster_name=~\"$cluster\"}[5m])) or on() vector(0)",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Workers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"worker\",cluster_name=~\"$cluster\"})",
     "legendFormat": "Live"
    },
    {
     "expr": "sum by () (prometheus_target_scrape_pool_targets{scrape_job=\"worker\"}) - sum by () (up{job=\"worker\",cluster_name=~\"$cluster\"})",
     "legendFormat": "Lost"
    }
   ]
  },
  {
   "title": "License (Valid To)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(alluxio_license_expiration_date{job=~\"coordinator|worker\"}) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Uptime",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "timestamp(process_start_time_seconds{job=~\"coordinator|worker|fuse\",cluster_name=~\"$cluster\"}) - process_start_time_seconds{job=~\"coordinator|worker|fuse\",cluster_name=~\"$cluster\"}",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Process Version",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (alluxio_version_info{cluster_name=~\"$cluster\"}) by (version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Hit(%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(alluxio_cached_data_read_bytes_total{job=\"worker\",cluster_name=~\"$cluster\"}[5m])) / (sum(irate(alluxio_cached_data_read_bytes_total{job=\"worker\",cluster_name=~\"$cluster\"}[5m])) + sum(irate(alluxio_missed_data_read_bytes_total{job=\"worker\",cluster_name=~\"$cluster\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Eviction",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(alluxio_cached_evicted_data_bytes_total{job=\"worker\",cluster_name=~\"$cluster\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput - Read",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(alluxio_data_throughput_bytes_total{job=\"worker\",method=\"read\",cluster_name=~\"$cluster\"}[5m])) or on() vector(0)",
     "legendFormat": "Worker"
    },
    {
     "expr": "sum(irate(alluxio_ufs_data_access_bytes_total{job=\"worker\",method=\"read\",cluster_name=~\"$cluster\"}[5m])) or on() vector(0)",
     "legendFormat": "UFS"
    }
   ]
  },
  {
   "title": "Throughput - Write",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(alluxio_ufs_data_access_bytes_total{job=\"worker\",method=\"write\",cluster_name=~\"$cluster\"}[5m])) or on() vector(0)",
     "legendFormat": "Worker"
    }
   ]
  },
  {
   "title": "Request/s - Read",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(alluxio_data_access_bytes_count{job=\"worker\",cluster_name=~\"$cluster\"}[5m]))",
     "legendFormat": "Worker"
    }
   ]
  },
  {
   "title": "Request/s - Metadata",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(alluxio_meta_operation_total{job=\"worker\",cluster_name=~\"$cluster\"}[5m])) or on() vector(0)",
     "legendFormat": "Worker"
    }
   ]
  },
  {
   "title": "Worker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Used",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "alluxio_cached_storage_bytes{job=\"worker\",instance=~\"$instance\",cluster_name=~\"$cluster\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Cache Evicted",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "irate(alluxio_cached_evicted_data_bytes_total{job=\"worker\",instance=~\"$instance\",cluster_name=~\"$cluster\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Throughput - Read",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "irate(alluxio_data_throughput_bytes_total{job=\"worker\",method=\"read\",cluster_name=~\"$cluster\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Throughput - Write",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "irate(alluxio_data_throughput_bytes_total{job=\"worker\",method=\"write\",cluster_name=~\"$cluster\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Request/s - Read",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "irate(alluxio_data_access_bytes_count{method=\"read\",job=\"worker\",instance=~\"$instance\",cluster_name=~\"$cluster\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Request/s - Metadata",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "irate(alluxio_meta_operation_total{job=\"worker\",instance=~\"$instance\",cluster_name=~\"$cluster\"}[5m])",
       "legendFormat": "{{instance}}-{{op}}"
      }
     ]
    },
    {
     "title": "Pages",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "alluxio_data_cached_pages{job=\"worker\",cluster_name=~\"$cluster\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "UFS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput - Read",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "irate(alluxio_ufs_data_access_bytes_total{method=\"read\",cluster_name=~\"$cluster\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Throughput - Write",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "irate(alluxio_ufs_data_access_bytes_total{method=\"write\",cluster_name=~\"$cluster\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(alluxio_ufs_error_total{}[5m])",
       "legendFormat": "{{job}}-{{instance}}-{{ufs_type}}-{{error_code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Distributed Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Distributed Load Operation Counts Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(alluxio_distributed_load_job_scanned_total{job=\"coordinator\", instance=~\"$instance\"}[5m])",
       "legendFormat": "File & Directory Scanned"
      },
      {
       "expr": "irate(alluxio_distributed_load_job_processed_total{job=\"coordinator\", instance=~\"$instance\"}[5m])",
       "legendFormat": "File & Directory Loaded"
      },
      {
       "expr": "irate(alluxio_distributed_load_job_skipped_total{job=\"coordinator\", instance=~\"$instance\"}[5m])",
       "legendFormat": "File & Directory Skipped"
      },
      {
       "expr": "sum by()(irate(alluxio_distributed_load_job_failure_total{job=\"coordinator\", instance=~\"$instance\"}[5m]))",
       "legendFormat": "File & Directory Errors"
      }
     ]
    },
    {
     "title": "Distributed Load Failure Breakdowns",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "expr": "sum by(reason, worker) (irate(alluxio_distributed_load_job_failure_total{job=\"coordinator\", instance=~\"$instance\"} [5m]))",
       "legendFormat": "{{reason}}-{{worker}}"
      }
     ]
    },
    {
     "title": "Job Dispatched Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "sum by(worker)(irate(alluxio_distributed_load_job_dispatched_size_total{job=\"coordinator\", instance=~\"$instance\"} [5m]))",
       "legendFormat": "{{worker}}"
      }
     ]
    },
    {
     "title": "Bytes Loaded on Workers Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(instance) (irate(alluxio_distributed_worker_bytes_loaded_bytes_total{job=\"worker\", instance=~\"$instance\"} [5m]))",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum by()(irate(alluxio_distributed_load_job_loaded_bytes_total{job=\"coordinator\", instance=~\"$instance\"} [5m]))",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  {
   "title": "Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU time spent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "irate(process_cpu_seconds_total{job=~\"$service\",instance=~\"$instance\",cluster_name=~\"$cluster\"}[5m])",
       "legendFormat": "{{job}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "targets": [
      {
       "expr": "jvm_threads_current{job=~\"$service\",instance=~\"$instance\",cluster_name=~\"$cluster\"}",
       "legendFormat": "{{job}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Heap Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{area=\"heap\",job=~\"$service\",instance=~\"$instance\",cluster_name=~\"$cluster\"}",
       "legendFormat": "{{job}}-{{instance}}"
      }
     ]
    },
    {
     "title": "Heap Usage(%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{area=\"heap\",job=~\"$service\",instance=~\"$instance\",cluster_name=~\"$cluster\"} / jvm_memory_max_bytes{area=\"heap\",job=~\"$service\",instance=~\"$instance\",cluster_name=~\"$cluster\"}",
       "legendFormat": "{{job}}-{{instance}}"
      }
     ]
    },
    {
     "title": "young GC time(per minute)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(jvm_gc_collection_seconds_sum{gc=\"G1 Young Generation\",job=~\"$service\",instance=~\"$instance\",cluster_name=~\"$cluster\"}[5m]) * 60",
       "legendFormat": "{{job}}-{{instance}}"
      }
     ]
    },
    {
     "title": "young GC rate(per minute)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "targets": [
      {
       "expr": "irate(jvm_gc_collection_seconds_count{gc=\"G1 Young Generation\",job=~\"$service\",instance=~\"$instance\",cluster_name=~\"$cluster\"}[5m]) * 60",
       "legendFormat": "{{job}}-{{instance}}"
      }
     ]
    },
    {
     "title": "old GC time(per minute)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(jvm_gc_collection_seconds_sum{gc=\"G1 Old Generation\",job=~\"$service\",instance=~\"$instance\",cluster_name=~\"$cluster\"}[5m]) * 60",
       "legendFormat": "{{job}}-{{instance}}"
      }
     ]
    },
    {
     "title": "old GC rate(per minute)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "targets": [
      {
       "expr": "irate(jvm_gc_collection_seconds_count{gc=\"G1 Old Generation\",job=~\"$service\",instance=~\"$instance\",cluster_name=~\"$cluster\"}[5m]) * 60",
       "legendFormat": "{{job}}-{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "ETCD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Up",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 46 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(etcd_server_has_leader{job=\"etcd\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RPC Rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 6, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_started_total{job=\"etcd\",grpc_type=\"unary\"}[5m]))",
       "legendFormat": "RPC Rate"
      },
      {
       "expr": "sum(rate(grpc_server_handled_total{job=\"etcd\",grpc_type=\"unary\",grpc_code!=\"OK\"}[5m]))",
       "legendFormat": "RPC Failed Rate"
      }
     ]
    },
    {
     "title": "Active Streams",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 46 },
     "targets": [
      {
       "expr": "sum(grpc_server_started_total{job=\"etcd\",grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"}) - sum(grpc_server_handled_total{job=\"etcd\",grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"})",
       "legendFormat": "Watch Streams"
      },
      {
       "expr": "sum(grpc_server_started_total{job=\"etcd\",grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\"}) - sum(grpc_server_handled_total{job=\"etcd\",grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\"})",
       "legendFormat": "Lease Streams"
      }
     ]
    },
    {
     "title": "DB Size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "etcd_mvcc_db_total_size_in_bytes{job=\"etcd\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk Sync Duration",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 52 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{job=\"etcd\"}[5m])) by (instance, le))",
       "legendFormat": "{{instance}} WAL fsync"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{job=\"etcd\"}[5m])) by (instance, le))",
       "legendFormat": "{{instance}} DB fsync"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"etcd\"}",
       "legendFormat": "{{instance}} Resident Memory"
      }
     ]
    },
    {
     "title": "Client Traffic In",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(etcd_network_client_grpc_received_bytes_total{job=\"etcd\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Client Traffic Out",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(etcd_network_client_grpc_sent_bytes_total{job=\"etcd\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Peer Traffic In",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(etcd_network_peer_received_bytes_total{job=\"etcd\"}[5m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Peer Traffic Out",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(etcd_network_peer_sent_bytes_total{job=\"etcd\"}[5m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Raft Proposals",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(etcd_server_proposals_failed_total{job=\"etcd\"}[5m]))",
       "legendFormat": "Proposal Failure Rate"
      },
      {
       "expr": "sum(etcd_server_proposals_pending{job=\"etcd\"})",
       "legendFormat": "Proposal Pending Total"
      },
      {
       "expr": "sum(rate(etcd_server_proposals_committed_total{job=\"etcd\"}[5m]))",
       "legendFormat": "Proposal Commit Rate"
      },
      {
       "expr": "sum(rate(etcd_server_proposals_applied_total{job=\"$cluster\"}[5m]))",
       "legendFormat": "Proposal Apply Rate"
      }
     ]
    },
    {
     "title": "Total Leader Elections Per Day",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 64 },
     "targets": [
      {
       "expr": "changes(etcd_server_leader_changes_seen_total{job=\"etcd\"}[1d])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}