{
 "title": "Alluxio Fuse Debug Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(up{job!=\"prometheus\"},job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job!=\"prometheus\"},instance)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"worker\"},cluster_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Fuse",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fuse open file count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "alluxio_fuse_open_files{job=\"fuse\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Fuse concurrency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "alluxio_fuse_concurrency{job=\"fuse\",instance=~\"$instance\"}",
       "legendFormat": "{{method}}({{instance}})"
      }
     ]
    },
    {
     "title": "BytesReadFromWorkers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "irate(alluxio_read_from_workers_bytes_total{job=\"fuse\",instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Fuse Call Success",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "irate(alluxio_fuse_call_latency_ms_count{job=\"fuse\", success=\"true\",instance=~\"$instance\"}[1m])",
       "legendFormat": "{{method}}({{instance}})"
      }
     ]
    },
    {
     "title": "Fuse Call fail",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "irate(alluxio_fuse_call_latency_ms_count{job=\"fuse\", success=\"false\",instance=~\"$instance\"}[1m])",
       "legendFormat": "{{method}}({{instance}})"
      }
     ]
    },
    {
     "title": "Fuse Call time(1min average)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "increase(alluxio_fuse_call_latency_ms_sum{job=\"fuse\", success=\"true\",instance=~\"$instance\"}[1m])/increase(alluxio_fuse_call_latency_ms_count{job=\"fuse\", success=\"true\",instance=~\"$instance\"}[1m])",
       "legendFormat": "{{method}}({{instance}})"
      }
     ]
    },
    {
     "title": "Fuse Call time（split by bucket）",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "irate(alluxio_fuse_call_latency_ms_bucket{job=\"fuse\", success=\"true\",instance=~\"$instance\"}[1m])",
       "legendFormat": "{{method}}[0, {{le}}]"
      }
     ]
    },
    {
     "title": "Fuse Random Read Buffer Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "irate(alluxio_fuse_buffer_size_bytes_bucket{job=\"fuse\",sequential=\"false\",instance=~\"$instance\",method=\"Fuse.Read\"}[1m])",
       "legendFormat": "[0, {{le}}]"
      }
     ]
    },
    {
     "title": "Fuse Sequential Read Buffer Size（split by bucket）",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "irate(alluxio_fuse_buffer_size_bytes_bucket{job=\"fuse\",sequential=\"true\",instance=~\"$instance\",method=\"Fuse.Read\"}[1m])",
       "legendFormat": "[0, {{le}}]"
      }
     ]
    },
    {
     "title": "Fuse Read Block Size（split by bucket）",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "irate(alluxio_fuse_block_size_bytes_bucket{job=\"fuse\",instance=~\"$instance\",method=\"Fuse.Read\"}[1m])",
       "legendFormat": "[0, {{le}}]"
      }
     ]
    },
    {
     "title": "Fuse call sequential read bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "irate(alluxio_fuse_buffer_size_bytes_sum{job=\"fuse\",sequential=\"true\",instance=~\"$instance\", method=\"Fuse.Read\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Fuse call random read bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "irate(alluxio_fuse_buffer_size_bytes_sum{job=\"fuse\",sequential=\"false\",instance=~\"$instance\",method=\"Fuse.Read\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Fuse Sequential Write Buffer Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "irate(alluxio_fuse_buffer_size_bytes_bucket{job=\"fuse\",sequential=\"true\",instance=~\"$instance\",method=\"Fuse.Write\"}[1m])",
       "legendFormat": "[0, {{le}}]"
      }
     ]
    },
    {
     "title": "Fuse call sequential write bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "irate(alluxio_fuse_buffer_size_bytes_sum{job=\"fuse\",sequential=\"true\",instance=~\"$instance\",method=\"Fuse.Write\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Fuse call random write bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "irate(alluxio_fuse_buffer_size_bytes_sum{job=\"fuse\",sequential=\"false\",instance=~\"$instance\",method=\"Fuse.Write\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Fuse call random write bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "irate(alluxio_fuse_buffer_size_bytes_sum{job=\"fuse\",sequential=\"false\",instance=~\"$instance\",method=\"Fuse.Write\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Fuse Write Block Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "irate(alluxio_fuse_block_size_bytes_bucket{job=\"fuse\",instance=~\"$instance\",method=\"Fuse.Write\"}[1m])",
       "legendFormat": "[0, {{le}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "AsyncPrefetch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "prefetch bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(irate(alluxio_async_prefetch_hit_cache_bytes_total{job=\"fuse\"}[1m]))",
       "legendFormat": "hit in cache"
      },
      {
       "expr": "sum(irate(alluxio_async_prefetch_cache_bytes_total{job=\"fuse\"}[1m]))",
       "legendFormat": "prefetch to cache"
      }
     ]
    },
    {
     "title": "async prefetch direct memory used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "alluxio_async_prefetch_direct_memory_used_bytes{job=\"fuse\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "async prefetch random read",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "irate(alluxio_async_prefetch_random_read_requests_total{job=\"fuse\",instance=~\"$instance\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Fuse Write Back",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Write back dir capacity&used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "alluxio_upload_manager_space_capacity_bytes{job=\"fuse\",instance=~\"$instance\"}",
       "legendFormat": "capacity"
      },
      {
       "expr": "alluxio_upload_manager_space_used_bytes{job=\"fuse\",instance=~\"$instance\"}",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Write back upload to ufs bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "irate(alluxio_upload_manager_write_to_ufs_bytes_total{job=\"fuse\",instance=~\"$instance\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Write back upload to ufs file status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "alluxio_upload_manager_upload_failed_files{job=\"fuse\",instance=~\"$instance\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "alluxio_upload_manager_pending_files{job=\"fuse\",instance=~\"$instance\"}",
       "legendFormat": "PendingFiles:{{state}}"
      }
     ]
    },
    {
     "title": "Write back upload to ufs tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "alluxio_upload_manager_tasks{job=\"fuse\",instance=~\"$instance\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "fallback to sync writes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "alluxio_write_back_fallback_to_sync_writes_total{job=\"fuse\",instance=~\"$instance\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "write back bloomfilter elements",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "alluxio_write_back_bloom_filter_approximate_elements{job=\"fuse\",instance=~\"$instance\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Write back bloom filter fpp",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "alluxio_write_back_bloom_filter_fpp{job=\"fuse\",instance=~\"$instance\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Write back cached directories",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "alluxio_write_back_bloom_filter_cached_directories{job=\"fuse\",instance=~\"$instance\"}",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Position Writer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Compaction tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "alluxio_position_write_compaction_tasks{job=\"fuse\",instance=~\"$instance\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Compaction task delete files",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "alluxio_position_write_compaction_delete_files_total{job=\"fuse\",instance=~\"$instance\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "local frames",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "alluxio_position_write_local_frames{job=\"fuse\",instance=~\"$instance\"}",
       "legendFormat": "{{frame_size}}:{{type}}"
      }
     ]
    },
    {
     "title": "Local write back position writes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "alluxio_position_write_local_write_back_position_writers{job=\"fuse\",instance=~\"$instance\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "position write written bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "alluxio_position_write_bytes_written_bytes_total{job=\"fuse\",instance=~\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "position write get status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "alluxio_position_write_get_status_total{job=\"fuse\",instance=~\"$instance\"}",
       "legendFormat": "position_write:{{position_write}}"
      }
     ]
    },
    {
     "title": "position write open files",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "alluxio_position_write_file_open_total{job=\"fuse\",instance=~\"$instance\"}",
       "legendFormat": "position_write:{{position_write}}"
      }
     ]
    },
    {
     "title": "position write write files",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "alluxio_position_write_file_write_total{job=\"fuse\",instance=~\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "position write read frames",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "alluxio_position_write_frames_read_total{job=\"fuse\",instance=~\"$instance\"}",
       "legendFormat": "{{source}}"
      }
     ]
    },
    {
     "title": "position write write frames",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "alluxio_position_write_frames_write_total{job=\"fuse\",instance=~\"$instance\"}",
       "legendFormat": "new_frame:{{new_frame}}"
      }
     ]
    }
   ]
  }
 ]
}